# Generated by Django 5.1.6 on 2025-03-08 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_order_item_userlocation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='category',
        ),
        migrations.DeleteModel(
            name='Team',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Dish',
        ),
    ]
