# Generated by Django 5.1.6 on 2025-03-08 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_remove_dish_category_delete_team_delete_category_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name_plural': 'Profile'},
        ),
    ]
