# Generated by Django 5.1.6 on 2025-03-08 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_profile_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user_type',
            field=models.CharField(blank=True, choices=[('customer', 'Customer'), ('restaurant', 'Restaurant')], max_length=15, null=True),
        ),
    ]
