# Generated by Django 5.1.7 on 2025-03-13 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_order_customer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
