# Generated by Django 5.1.6 on 2025-02-27 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_alter_restaurant_latitude_alter_restaurant_longitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='distance_from_user',
        ),
        migrations.RemoveField(
            model_name='item',
            name='category',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='facilities',
            field=models.ManyToManyField(related_name='restaurants', to='restaurant.facility'),
        ),
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.ManyToManyField(related_name='items', to='restaurant.category'),
        ),
    ]
