# Generated by Django 5.1.6 on 2025-02-27 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_facility_remove_restaurant_distance_from_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='is_open',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='longitude',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='about',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='closes_at',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='opens_at',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
