# Generated by Django 5.1.6 on 2025-02-27 16:29

import restaurant.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0007_restaurant_is_open'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=restaurant.models.category_image_path),
        ),
    ]
