# Generated by Django 5.1.7 on 2025-03-14 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_remove_cart_session_key_order_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='payment_id',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='payment_signature',
        ),
    ]
