# Generated by Django 5.1.7 on 2025-03-20 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_remove_cart_payment_id_remove_cart_payment_signature'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='status',
            new_name='payment_status',
        ),
    ]
