# Generated by Django 5.1.7 on 2025-03-20 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_rename_status_order_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('cancelled', 'Cancelled'), ('preparing', 'Preparing'), ('on_the_way', 'On The Way'), ('delivered', 'Delivered')], default='cancelled', max_length=20),
        ),
    ]
